#!/usr/bin/env sh
# place this file in .config/limelight/

limelight -m config width            1 
limelight -m config radius           0
limelight -m config placement        interior 
limelight -m config active_color     0xff775759
limelight -m config normal_color     0xff555555

echo "limelight configuration loaded.."
