#!/usr/bin/env sh
# place this file in .config/limelight/

limelight -m config width            4 
limelight -m config radius           0
limelight -m config placement        inset
limelight -m config active_color     0xff4c7f99
limelight -m config normal_color     0xff555555

echo "limelight configuration loaded.."
