general.import = ["/Users/maclarel/.config/alacritty/themes/solarized_dark.toml"]

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[window]
decorations = "buttonless"
opacity = 0.95

[window.padding]
x = 5
y = 5

[selection]
save_to_clipboard = true

[font]
size = 16.0
normal = { family = "Hack Nerd Font Mono", style = "Regular" }

# Colors (Nord)

# Default colors
[colors.primary]
background = '#2E3440'
foreground = '#D8DEE9'

# Normal colors
[colors.normal]
black   = '#3B4252'
red     = '#BF616A'
green   = '#A3BE8C'
yellow  = '#EBCB8B'
blue    = '#81A1C1'
magenta = '#B48EAD'
cyan    = '#88C0D0'
white   = '#E5E9F0'

# Bright colors
[colors.bright]
black   = '#4C566A'
red     = '#BF616A'
green   = '#A3BE8C'
yellow  = '#EBCB8B'
blue    = '#81A1C1'
magenta = '#B48EAD'
cyan    = '#8FBCBB'
white   = '#ECEFF4'
